import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IconComponent } from '../../component/icon/icon';
import { NotifyDataService } from '../../services/notify-data.service';

@Component({
    selector: 'app-tasks', standalone: true, imports: [FormsModule, IconComponent],
    template: `<section class="page"><header class="page-head"><div><p class="eyebrow">Make progress, one step at a time</p><h1>Tasks</h1></div><button class="primary" (click)="adding = !adding"><app-icon name="plus" /> Add Task</button></header>
  @if (adding) { <form class="composer" (ngSubmit)="add()"><input name="title" [(ngModel)]="title" placeholder="What needs doing?" required><input name="due" type="datetime-local" [(ngModel)]="due"><button class="primary" type="submit" aria-label="Save task" title="Save task"><app-icon name="check" /></button></form> }
  <div class="tabs"><button [class.selected]="filter === 'all'" (click)="filter = 'all'">All</button><button [class.selected]="filter === 'pending'" (click)="filter = 'pending'">Pending</button><button [class.selected]="filter === 'completed'" (click)="filter = 'completed'">Completed</button><label>Sort by <select [(ngModel)]="sort" name="sort"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="title">Title</option></select></label></div>
  <section class="panel">@for (task of visibleTasks(); track task.id) { <div class="task">@if (editingId === task.id) { <form class="edit-form" (ngSubmit)="saveEdit(task.id)"><input name="editTaskTitle" [(ngModel)]="editTitle" required><input name="editTaskDue" type="datetime-local" [(ngModel)]="editDue"><button class="save">Save</button><button type="button" class="cancel" (click)="cancelEdit()">Cancel</button></form> } @else { <button class="check" [class.done]="task.completed" (click)="data.toggleTask(task.id)">@if (task.completed) {✓}</button><strong [class.strike]="task.completed">{{ task.title }}</strong><small>{{ displayDate(task.due) }}</small><span class="status" [class.completed]="task.completed">{{ task.completed ? 'Completed' : 'Pending' }}</span><button class="edit" (click)="startEdit(task)" aria-label="Edit task"><app-icon name="edit" /></button><button class="delete" (click)="data.removeTask(task.id)" aria-label="Delete task"><app-icon name="trash" /></button> } </div> }</section></section>`,
    styles: [`.page{max-width:1000px;margin:auto;padding:var(--space-page-y) var(--space-page-x)}.page-head{display:flex;justify-content:space-between;align-items:center}.eyebrow{font-size:10px;color:var(--color-muted);margin:0 0 5px}.page-head h1{font:700 20px 'Space Grotesk';margin:0}.primary{background:var(--color-blue);color:var(--color-surface);border:0;border-radius:5px;padding:var(--space-2) var(--space-control-wide);font-size:10px;display:flex;gap:var(--space-1);align-items:center}.composer{display:flex;gap:var(--space-2);flex-wrap:wrap;background:var(--color-surface);border:1px solid var(--color-border-soft);padding:var(--space-3);margin-top:16px;border-radius:8px}.composer input,.edit-form input{flex:1;min-width:160px;border:1px solid var(--color-border-soft);border-radius:5px;padding:9px;font-size:11px}.tabs{display:flex;align-items:center;gap:var(--space-5);padding:25px 0 11px;font-size:10px;color:var(--color-control)}.tabs button{border:0;background:none;padding:0 0 8px;color:inherit}.tabs .selected{color:var(--color-blue);font-weight:600;border-bottom:2px solid var(--color-blue)}.tabs label{margin-left:auto;display:flex;gap:var(--space-1);align-items:center}.tabs select{border:0;background:transparent;color:var(--color-control);font-size:10px}.panel{background:var(--color-surface);border:1px solid var(--color-border-soft);border-radius:9px;padding:0 12px}.task{min-height:48px;display:grid;grid-template-columns:22px 1fr 185px 68px 22px 22px;align-items:center;gap:var(--space-2);border-bottom:1px solid var(--color-divider);font-size:10px}.task:last-child{border:0}.check{width:13px;height:13px;padding:0;border:1px solid var(--color-control);background:var(--color-surface);border-radius:3px;color:var(--color-surface);font-size:9px}.check.done{background:var(--color-green);border-color:var(--color-green)}.strike{text-decoration:line-through;color:var(--color-control)}.task small{color:var(--color-muted);font-size:9px}.status{justify-self:start;background:var(--color-yellow-soft);color:var(--color-yellow);padding:4px 8px;border-radius:9px;font-size:8px}.status.completed{background:var(--color-green-pale);color:var(--color-green)}.edit,.delete,.save,.cancel{border:0;background:none;color:var(--color-control);padding:5px;border-radius:4px}.delete:hover{color:var(--color-red);background:var(--color-red-soft)}.edit-form{grid-column:1/-1;display:flex;gap:var(--space-2);align-items:center;padding:var(--space-2) 0}.edit-form .save{color:var(--color-blue)}.edit-form .cancel{color:var(--color-control)}@media(max-width:700px){.page{padding:var(--space-page-y) 14px}.task{grid-template-columns:22px 1fr 22px 22px}.task small,.status{display:none}.tabs{gap:var(--space-3)}.tabs label{margin-left:0}}`]
})
export class TasksPage {
    readonly data = inject(NotifyDataService); title = ''; due = ''; adding = false; filter: 'all' | 'pending' | 'completed' = 'all'; sort: 'newest' | 'oldest' | 'title' = 'newest'; editingId: number | null = null; editTitle = ''; editDue = '';
    visibleTasks = () => [...this.data.tasks().filter(task => this.filter === 'all' || (this.filter === 'completed' ? task.completed : !task.completed))].sort((first, second) => this.sort === 'title' ? first.title.localeCompare(second.title) : this.sort === 'newest' ? second.id - first.id : first.id - second.id);
    add() { if (this.title.trim()) { this.data.addTask(this.title.trim(), this.due || 'No reminder'); this.title = ''; this.due = ''; this.adding = false; } }
    startEdit(task: { id: number; title: string; due: string }) { this.editingId = task.id; this.editTitle = task.title; this.editDue = this.toInput(task.due); }
    saveEdit(id: number) { if (this.editTitle.trim()) { this.data.updateTask(id, this.editTitle.trim(), this.editDue || 'No reminder'); this.cancelEdit(); } }
    cancelEdit() { this.editingId = null; this.editTitle = ''; this.editDue = ''; }
    displayDate(value: string) { if (value === 'No reminder' || !value) return 'No reminder'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }); }
    private toInput(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
}
