import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IconComponent } from '../../component/icon/icon';
import { NotifyDataService } from '../../services/notify-data.service';

@Component({
  selector: 'app-notes', standalone: true, imports: [FormsModule, IconComponent],
  template: `<section class="page">
    <header class="page-head"><div><p class="eyebrow">Your thoughts, organized</p><h1>Notes</h1></div><button class="primary" (click)="adding = !adding"><app-icon name="plus" /> Add Note</button></header>
    @if (adding) { <form class="composer" (ngSubmit)="add()"><input name="title" [(ngModel)]="title" placeholder="Note title" required><textarea name="body" [(ngModel)]="body" placeholder="Write something..."></textarea><button class="primary" type="submit" aria-label="Save note" title="Save note"><app-icon name="check" /></button></form> }
    <div class="toolbar"><label><span>⌕</span><input [(ngModel)]="query" placeholder="Search notes..."></label><button class="view" [class.active]="view === 'grid'" (click)="view = 'grid'" aria-label="Grid view"><app-icon name="grid" /></button><button class="view" [class.active]="view === 'list'" (click)="view = 'list'" aria-label="List view"><app-icon name="list" /></button></div>
    <div class="notes-grid" [class.list-view]="view === 'list'">@for (note of filtered(); track note.id) { <article class="note-card {{ note.tone }}">@if (editingId === note.id) { <form class="edit-form" (ngSubmit)="saveEdit(note.id)"><input name="editTitle" [(ngModel)]="editTitle" required><textarea name="editBody" [(ngModel)]="editBody"></textarea><div><button class="save" type="submit" aria-label="Save note" title="Save note"><app-icon name="check" /></button><button class="cancel" type="button" (click)="cancelEdit()" aria-label="Cancel editing" title="Cancel editing"><app-icon name="x" /></button></div></form> } @else { <button class="dots" aria-label="Edit note" (click)="startEdit(note)"><app-icon name="edit" /></button><h2>{{ note.title }}</h2><p>{{ note.body }}</p><footer><span>{{ note.date }} · {{ note.time }}</span><button class="delete" (click)="data.removeNote(note.id)" aria-label="Delete note"><app-icon name="trash" /></button></footer> }</article> }</div>
  </section>`,
  styles: [`.page{max-width:1000px;margin:auto;padding:var(--space-page-y) var(--space-page-x) 50px}.page-head{display:flex;justify-content:space-between;align-items:center}.eyebrow{font-size:10px;color:var(--color-muted);margin:0 0 5px}.page-head h1{font:700 20px 'Space Grotesk';margin:0}.primary{background:var(--color-blue);color:var(--color-surface);border:0;border-radius:5px;padding:var(--space-2) var(--space-control-wide);font-size:10px;display:flex;gap:var(--space-1);align-items:center;box-shadow:0 4px 10px var(--color-blue)33}.composer,.edit-form{display:grid;gap:var(--space-2);background:var(--color-surface);border:1px solid var(--color-border-soft);padding:var(--space-3);margin-top:16px;border-radius:8px}.composer input,.composer textarea,.edit-form input,.edit-form textarea{border:1px solid var(--color-border-soft);border-radius:5px;padding:9px;font-size:11px}.composer textarea,.edit-form textarea{min-height:60px;resize:vertical}.composer .primary{justify-self:end}.toolbar{display:flex;gap:7px;margin:22px 0 15px}.toolbar label{display:flex;align-items:center;gap:var(--space-1);border:1px solid var(--color-border);border-radius:7px;background:var(--color-surface);padding:0 10px;flex:1;max-width:300px}.toolbar input{border:0;outline:0;padding:9px 0;font-size:10px;width:100%}.view{width:31px;border:1px solid var(--color-border);background:var(--color-surface);border-radius:6px;color:var(--color-control)}.view.active{background:var(--color-blue-soft);color:var(--color-blue)}.notes-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:var(--space-3)}.notes-grid.list-view{grid-template-columns:1fr}.note-card{position:relative;min-height:150px;padding:var(--space-card);border:1px solid var(--color-border);border-top:2px solid;border-radius:7px;background:var(--color-surface);box-shadow:0 4px 15px var(--shadow-card)}.note-card.blue{border-color:var(--color-blue-border)}.note-card.pink{border-color:var(--color-purple)}.note-card.yellow{border-color:var(--color-yellow)}.note-card h2{font:600 11px 'Space Grotesk';margin:0 0 9px}.note-card p{font-size:10px;line-height:1.5;color:var(--color-body);white-space:pre-line;margin:0}.dots{position:absolute;right:9px;top:9px;border:0;background:none;color:var(--color-control)}.note-card footer{position:absolute;bottom:10px;left:14px;right:10px;display:flex;justify-content:space-between;align-items:center;color:var(--color-faint);font-size:8px}.delete,.edit-form button{border:0;background:none;color:var(--color-control);padding:5px;border-radius:4px}.delete:hover{color:var(--color-red);background:var(--color-red-soft)}.edit-form{margin:0;background:transparent;border:0;padding:0}.edit-form div{display:flex;gap:var(--space-control)}.edit-form .save{color:var(--color-blue)}.edit-form .cancel{color:var(--color-control)}@media(max-width:700px){.page{padding:var(--space-page-y) 14px}.notes-grid{grid-template-columns:1fr 1fr}}@media(max-width:420px){.notes-grid{grid-template-columns:1fr}}`]
})
export class NotesPage {
  readonly data = inject(NotifyDataService); title = ''; body = ''; query = ''; adding = false; view: 'grid' | 'list' = 'grid'; editingId: number | null = null; editTitle = ''; editBody = '';
  filtered = () => this.data.notes().filter(note => `${note.title} ${note.body}`.toLowerCase().includes(this.query.toLowerCase()));
  add() { if (this.title.trim()) { this.data.addNote(this.title.trim(), this.body.trim()); this.title = ''; this.body = ''; this.adding = false; } }
  startEdit(note: { id: number; title: string; body: string }) { this.editingId = note.id; this.editTitle = note.title; this.editBody = note.body; }
  saveEdit(id: number) { if (this.editTitle.trim()) { this.data.updateNote(id, this.editTitle.trim(), this.editBody.trim()); this.cancelEdit(); } }
  cancelEdit() { this.editingId = null; this.editTitle = ''; this.editBody = ''; }
}
