import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IconComponent } from '../../component/icon/icon';
import { NotifyDataService } from '../../services/notify-data.service';

@Component({
    selector: 'app-alerts', standalone: true, imports: [FormsModule, IconComponent],
    template: `<section class="page"><header class="page-head"><div><p class="eyebrow">Stay on top of what matters</p><h1>Alerts</h1></div><button class="primary" (click)="adding = !adding"><app-icon name="plus" /> Add Alert</button></header>
  @if (adding) { <form class="composer" (ngSubmit)="add()"><input name="title" [(ngModel)]="title" placeholder="Alert title" required><input name="date" type="datetime-local" [(ngModel)]="date"><button class="primary" type="submit" aria-label="Save alert" title="Save alert"><app-icon name="check" /></button></form> }
  <h2>Active Alerts</h2><section class="panel">@for (alert of data.alerts(); track alert.id) { <div class="alert-row">@if (editingId === alert.id) { <form class="edit-form" (ngSubmit)="saveEdit(alert.id)"><input name="editAlertTitle" [(ngModel)]="editTitle" required><input name="editAlertDate" type="datetime-local" [(ngModel)]="editDate"><button class="save">Save</button><button type="button" class="cancel" (click)="cancelEdit()">Cancel</button></form> } @else { <span class="alert-icon {{ alert.tone }}"><app-icon name="alerts" /></span><div><strong>{{ alert.title }}</strong><small>{{ displayDate(alert.date) }}</small></div><button class="trigger" (click)="triggered = alert.id">{{ triggered === alert.id ? 'Triggered' : 'Trigger Now' }}</button><button class="edit" (click)="startEdit(alert)" aria-label="Edit alert"><app-icon name="edit" /></button><button class="delete" (click)="data.removeAlert(alert.id)" aria-label="Delete alert"><app-icon name="trash" /></button> } </div> }</section><div class="info"><app-icon name="about" /> When an alert time is reached, you'll see a notification.</div></section>`,
    styles: [`.page{max-width:1000px;margin:auto;padding:var(--space-page-y) var(--space-page-x)}.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}.eyebrow{font-size:10px;color:var(--color-muted);margin:0 0 5px}.page-head h1{font:700 20px 'Space Grotesk';margin:0}.primary{background:var(--color-blue);color:var(--color-surface);border:0;border-radius:5px;padding:var(--space-2) var(--space-control-wide);font-size:10px;display:flex;gap:var(--space-1);align-items:center}.composer{display:flex;gap:var(--space-2);flex-wrap:wrap;background:var(--color-surface);border:1px solid var(--color-border-soft);padding:var(--space-3);margin-top:16px;margin-bottom:22px;border-radius:8px}.composer input,.edit-form input{flex:1;min-width:160px;border:1px solid var(--color-border-soft);border-radius:5px;padding:9px;font-size:11px}.page h2{font:600 13px 'Space Grotesk';margin:0 0 10px}.panel{background:var(--color-surface);border:1px solid var(--color-border-soft);border-radius:9px;padding:0 12px}.alert-row{display:flex;align-items:center;gap:var(--space-control);padding:var(--space-3) 0;border-bottom:1px solid var(--color-divider)}.alert-row:last-child{border:0}.alert-icon{width:28px;height:28px;border-radius:50%;display:grid;place-items:center}.alert-icon.purple{background:var(--color-purple-soft);color:var(--color-purple)}.alert-icon.orange{background:var(--color-orange-soft);color:var(--color-orange)}.alert-icon.blue{background:var(--color-blue-pale);color:var(--color-blue)}.alert-row div{flex:1}.alert-row strong,.alert-row small{display:block}.alert-row strong{font-size:10px}.alert-row small{font-size:9px;color:var(--color-muted);margin-top:3px}.trigger{border:0;background:var(--color-purple-soft);color:var(--color-purple);border-radius:8px;padding:6px 10px;font-size:9px}.delete,.edit,.save,.cancel{border:0;background:none;color:var(--color-control);padding:5px;border-radius:4px}.delete:hover{color:var(--color-red);background:var(--color-red-soft)}.edit-form{display:flex;gap:var(--space-2);align-items:center;width:100%}.edit-form .save{color:var(--color-blue)}.edit-form .cancel{color:var(--color-control)}.info{display:flex;align-items:center;gap:7px;background:var(--color-blue-soft);color:var(--color-blue);border-radius:7px;font-size:9px;padding:var(--space-control-wide);margin-top:14px}@media(max-width:700px){.page{padding:var(--space-page-y) 14px}.edit-form input{min-width:0;width:40%}.alert-row{gap:var(--space-compact)}}`]
})
export class AlertsPage {
    readonly data = inject(NotifyDataService); adding = false; title = ''; date = ''; triggered: number | null = null; editingId: number | null = null; editTitle = ''; editDate = '';
    add() { if (this.title.trim()) { this.data.addAlert(this.title.trim(), this.date || 'No scheduled time'); this.title = ''; this.date = ''; this.adding = false; } }
    startEdit(alert: { id: number; title: string; date: string }) { this.editingId = alert.id; this.editTitle = alert.title; this.editDate = this.toInput(alert.date); }
    saveEdit(id: number) { if (this.editTitle.trim()) { this.data.updateAlert(id, this.editTitle.trim(), this.editDate || 'No scheduled time'); this.cancelEdit(); } }
    cancelEdit() { this.editingId = null; this.editTitle = ''; this.editDate = ''; }
    displayDate(value: string) { if (value === 'No scheduled time' || !value) return 'No scheduled time'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }); }
    private toInput(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
}
